### ISSUE TITLE
SerialFLashStorage with SDU

### ISSUE THREAD

**Issue by DylanMeng** [arduino-libraries/WiFi101OTA#12]
Hi,

I am trying to use SerialFLashStorage, the copy process is working. The update.bin file is fully copied on the SPI flash, but I am not quite sure on how the get the SDU to work.

Do I need to change the SDU to work with SerialFLash?

Thanks!

**Comment by facchinm** [comment]
Hi @DylanMeng ,
we are developing a bunch of frontends to for OTA. I'm attaching a stub of SFU (SerialFlash based).
Let me know if it works for you!
[SFU.zip](https://github.com/arduino-libraries/WiFi101OTA/files/2561881/SFU.zip)

**Comment by DylanMeng** [comment]
@facchinm Yes it is fully working, thanks for the help!
