### ISSUE TITLE
Compatibility with other SAMD21 boards + ATWINC1500 breakout?

### ISSUE THREAD

**Issue by dwblair** [arduino-libraries/WiFi101OTA#5]
Hi!

This functionality is fantastic.  

Is it possible to use this library on a SAMD21 board like the Feather M0, with an ATWINC1500 breakout?  If so, I'm wondering which wires need to be connected :)  I'm guessing that the WiFi101OTA library makes a particular choice of CS pin for the SPI interface; but does it also require e.g. wiring up to RX / TX?

Cheers, and thanks for this great work!

**Comment by facchinm** [comment]
Hi @dwblair ,
if you want to use the internal storage for OTA you simply need to connect the module as you would use it normally, using the overloaded `begin()` function.

**Comment by dwblair** [comment]
Hi @facchinm  --  Thank you -- I tried it, and it works brilliantly!  Still seems like magic to me -- thanks thanks!

**Comment by facchinm** [comment]
Closing as solved :smile:
