### ISSUE TITLE
Using library with PlatformIO

### ISSUE THREAD

**Issue by griffingdm** [arduino-libraries/WiFi101OTA#8]
This works great with the Arduino IDE (Because Arduino IDE automatically shows selectable network ports), but I can't get it to work with Pio. 
(For reference I'm running the WiFi101_OTA example in ArduinoIDE and PlatformIO on a Feather M0 with an ATWINC1500)

In terminal:
`platformio run --target upload --upload-port IPADDRESS`

Returns "Could not find board on selected port."

Is there a default port number or a different IPAddress besides the WiFi.localIP() I should be using? 
This would save so much hassle converting sketches to compile in the ArduinoIDE in order to upload ota.

**Comment by sandeepmistry** [comment]
Hi @griffingdm,

This library uses the same discovery mechanism as other OTA boards, but a different HTTP based upload mechanism is used.

https://github.com/arduino/ArduinoCore-samd/blob/master/platform.txt#L144

The `arduinoOTA` tool bundled with the Arduino IDE can be used to upload via the command line: 

```
<path to tool>/bin/arduinoOTA -address <IP address> -port 65280 -username arduino -password "<password>" -sketch "<sketch binary path>.bin" -upload /sketch -b
```

**Comment by griffingdm** [comment]
So I cannot upload this ota with anything but the Arduino IDE due to its upload mechanism?

**Comment by sandeepmistry** [comment]
You can use the same tool the IDE uses from the command line: https://github.com/arduino/arduinoOTA/releases

Or make your own using HTTP.
